#!/usr/bin/env python3
# coding: utf-8
if '__PHP2PY_LOADED__' not in globals():
    import os
    with open(os.getenv('PHP2PY_COMPAT', 'php_compat.py')) as f:
        exec(compile(f.read(), '<string>', 'exec'))
    # end with
    globals()['__PHP2PY_LOADED__'] = True
# end if
#// 
#// Error Protection API: WP_Recovery_Mode_Key_Service class
#// 
#// @package WordPress
#// @since 5.2.0
#// 
#// 
#// Core class used to generate and validate keys used to enter Recovery Mode.
#// 
#// @since 5.2.0
#//
class WP_Recovery_Mode_Key_Service():
    #// 
    #// The option name used to store the keys.
    #// 
    #// @since 5.2.0
    #// @var string
    #//
    option_name = "recovery_keys"
    #// 
    #// Creates a recovery mode token.
    #// 
    #// @since 5.2.0
    #// 
    #// @return string $token A random string to identify its associated key in storage.
    #//
    def generate_recovery_mode_token(self):
        
        
        return wp_generate_password(22, False)
    # end def generate_recovery_mode_token
    #// 
    #// Creates a recovery mode key.
    #// 
    #// @since 5.2.0
    #// 
    #// @global PasswordHash $wp_hasher
    #// 
    #// @param string $token A token generated by {@see generate_recovery_mode_token()}.
    #// @return string $key Recovery mode key.
    #//
    def generate_and_store_recovery_mode_key(self, token_=None):
        
        
        global wp_hasher_
        php_check_if_defined("wp_hasher_")
        key_ = wp_generate_password(22, False)
        if php_empty(lambda : wp_hasher_):
            php_include_file(ABSPATH + WPINC + "/class-phpass.php", once=True)
            wp_hasher_ = php_new_class("PasswordHash", lambda : PasswordHash(8, True))
        # end if
        hashed_ = wp_hasher_.hashpassword(key_)
        records_ = self.get_keys()
        records_[token_] = Array({"hashed_key": hashed_, "created_at": time()})
        self.update_keys(records_)
        #// 
        #// Fires when a recovery mode key is generated.
        #// 
        #// @since 5.2.0
        #// 
        #// @param string $token The recovery data token.
        #// @param string $key   The recovery mode key.
        #//
        do_action("generate_recovery_mode_key", token_, key_)
        return key_
    # end def generate_and_store_recovery_mode_key
    #// 
    #// Verifies if the recovery mode key is correct.
    #// 
    #// Recovery mode keys can only be used once; the key will be consumed in the process.
    #// 
    #// @since 5.2.0
    #// 
    #// @param string $token The token used when generating the given key.
    #// @param string $key   The unhashed key.
    #// @param int    $ttl   Time in seconds for the key to be valid for.
    #// @return true|WP_Error True on success, error object on failure.
    #//
    def validate_recovery_mode_key(self, token_=None, key_=None, ttl_=None):
        
        
        records_ = self.get_keys()
        if (not (php_isset(lambda : records_[token_]))):
            return php_new_class("WP_Error", lambda : WP_Error("token_not_found", __("Recovery Mode not initialized.")))
        # end if
        record_ = records_[token_]
        self.remove_key(token_)
        if (not php_is_array(record_)) or (not (php_isset(lambda : record_["hashed_key"]) and php_isset(lambda : record_["created_at"]))):
            return php_new_class("WP_Error", lambda : WP_Error("invalid_recovery_key_format", __("Invalid recovery key format.")))
        # end if
        if (not wp_check_password(key_, record_["hashed_key"])):
            return php_new_class("WP_Error", lambda : WP_Error("hash_mismatch", __("Invalid recovery key.")))
        # end if
        if time() > record_["created_at"] + ttl_:
            return php_new_class("WP_Error", lambda : WP_Error("key_expired", __("Recovery key expired.")))
        # end if
        return True
    # end def validate_recovery_mode_key
    #// 
    #// Removes expired recovery mode keys.
    #// 
    #// @since 5.2.0
    #// 
    #// @param int $ttl Time in seconds for the keys to be valid for.
    #//
    def clean_expired_keys(self, ttl_=None):
        
        
        records_ = self.get_keys()
        for key_,record_ in records_:
            if (not (php_isset(lambda : record_["created_at"]))) or time() > record_["created_at"] + ttl_:
                records_[key_] = None
            # end if
        # end for
        self.update_keys(records_)
    # end def clean_expired_keys
    #// 
    #// Removes a used recovery key.
    #// 
    #// @since 5.2.0
    #// 
    #// @param string $token The token used when generating a recovery mode key.
    #//
    def remove_key(self, token_=None):
        
        
        records_ = self.get_keys()
        if (not (php_isset(lambda : records_[token_]))):
            return
        # end if
        records_[token_] = None
        self.update_keys(records_)
    # end def remove_key
    #// 
    #// Gets the recovery key records.
    #// 
    #// @since 5.2.0
    #// 
    #// @return array Associative array of $token => $data pairs, where $data has keys 'hashed_key'
    #// and 'created_at'.
    #//
    def get_keys(self):
        
        
        return get_option(self.option_name, Array())
    # end def get_keys
    #// 
    #// Updates the recovery key records.
    #// 
    #// @since 5.2.0
    #// 
    #// @param array $keys Associative array of $token => $data pairs, where $data has keys 'hashed_key'
    #// and 'created_at'.
    #// @return bool True on success, false on failure.
    #//
    def update_keys(self, keys_=None):
        
        
        return update_option(self.option_name, keys_)
    # end def update_keys
# end class WP_Recovery_Mode_Key_Service
