#!/usr/bin/env python3
# coding: utf-8
if '__PHP2PY_LOADED__' not in globals():
    import cgi
    import os
    import os.path
    import copy
    import sys
    from goto import with_goto
    with open(os.getenv('PHP2PY_COMPAT', 'php_compat.py')) as f:
        exec(compile(f.read(), '<string>', 'exec'))
    # end with
    globals()['__PHP2PY_LOADED__'] = True
# end if
if not php_defined("Sodium"):
    class Sodium:
        pass
    # end class
# end if
class Sodium(Sodium):
    _namespace__ = "Sodium"
    php_include_file(php_dirname(php_dirname(__FILE__)) + "/autoload.php", once=True)
    ParagonIE_Sodium_Compat = php_new_class("ParagonIE_Sodium_Compat", lambda *args, **kwargs: ParagonIE_Sodium_Compat(*args, **kwargs))
    CRYPTO_AEAD_AES256GCM_KEYBYTES = ParagonIE_Sodium_Compat.CRYPTO_AEAD_AES256GCM_KEYBYTES
    CRYPTO_AEAD_AES256GCM_NSECBYTES = ParagonIE_Sodium_Compat.CRYPTO_AEAD_AES256GCM_NSECBYTES
    CRYPTO_AEAD_AES256GCM_NPUBBYTES = ParagonIE_Sodium_Compat.CRYPTO_AEAD_AES256GCM_NPUBBYTES
    CRYPTO_AEAD_AES256GCM_ABYTES = ParagonIE_Sodium_Compat.CRYPTO_AEAD_AES256GCM_ABYTES
    CRYPTO_AEAD_CHACHA20POLY1305_KEYBYTES = ParagonIE_Sodium_Compat.CRYPTO_AEAD_CHACHA20POLY1305_KEYBYTES
    CRYPTO_AEAD_CHACHA20POLY1305_NSECBYTES = ParagonIE_Sodium_Compat.CRYPTO_AEAD_CHACHA20POLY1305_NSECBYTES
    CRYPTO_AEAD_CHACHA20POLY1305_NPUBBYTES = ParagonIE_Sodium_Compat.CRYPTO_AEAD_CHACHA20POLY1305_NPUBBYTES
    CRYPTO_AEAD_CHACHA20POLY1305_ABYTES = ParagonIE_Sodium_Compat.CRYPTO_AEAD_CHACHA20POLY1305_ABYTES
    CRYPTO_AEAD_CHACHA20POLY1305_IETF_KEYBYTES = ParagonIE_Sodium_Compat.CRYPTO_AEAD_CHACHA20POLY1305_IETF_KEYBYTES
    CRYPTO_AEAD_CHACHA20POLY1305_IETF_NSECBYTES = ParagonIE_Sodium_Compat.CRYPTO_AEAD_CHACHA20POLY1305_IETF_NSECBYTES
    CRYPTO_AEAD_CHACHA20POLY1305_IETF_NPUBBYTES = ParagonIE_Sodium_Compat.CRYPTO_AEAD_CHACHA20POLY1305_IETF_NPUBBYTES
    CRYPTO_AEAD_CHACHA20POLY1305_IETF_ABYTES = ParagonIE_Sodium_Compat.CRYPTO_AEAD_CHACHA20POLY1305_IETF_ABYTES
    CRYPTO_AUTH_BYTES = ParagonIE_Sodium_Compat.CRYPTO_AUTH_BYTES
    CRYPTO_AUTH_KEYBYTES = ParagonIE_Sodium_Compat.CRYPTO_AUTH_KEYBYTES
    CRYPTO_BOX_SEALBYTES = ParagonIE_Sodium_Compat.CRYPTO_BOX_SEALBYTES
    CRYPTO_BOX_SECRETKEYBYTES = ParagonIE_Sodium_Compat.CRYPTO_BOX_SECRETKEYBYTES
    CRYPTO_BOX_PUBLICKEYBYTES = ParagonIE_Sodium_Compat.CRYPTO_BOX_PUBLICKEYBYTES
    CRYPTO_BOX_KEYPAIRBYTES = ParagonIE_Sodium_Compat.CRYPTO_BOX_KEYPAIRBYTES
    CRYPTO_BOX_MACBYTES = ParagonIE_Sodium_Compat.CRYPTO_BOX_MACBYTES
    CRYPTO_BOX_NONCEBYTES = ParagonIE_Sodium_Compat.CRYPTO_BOX_NONCEBYTES
    CRYPTO_BOX_SEEDBYTES = ParagonIE_Sodium_Compat.CRYPTO_BOX_SEEDBYTES
    CRYPTO_KX_BYTES = ParagonIE_Sodium_Compat.CRYPTO_KX_BYTES
    CRYPTO_KX_SEEDBYTES = ParagonIE_Sodium_Compat.CRYPTO_KX_SEEDBYTES
    CRYPTO_KX_PUBLICKEYBYTES = ParagonIE_Sodium_Compat.CRYPTO_KX_PUBLICKEYBYTES
    CRYPTO_KX_SECRETKEYBYTES = ParagonIE_Sodium_Compat.CRYPTO_KX_SECRETKEYBYTES
    CRYPTO_GENERICHASH_BYTES = ParagonIE_Sodium_Compat.CRYPTO_GENERICHASH_BYTES
    CRYPTO_GENERICHASH_BYTES_MIN = ParagonIE_Sodium_Compat.CRYPTO_GENERICHASH_BYTES_MIN
    CRYPTO_GENERICHASH_BYTES_MAX = ParagonIE_Sodium_Compat.CRYPTO_GENERICHASH_BYTES_MAX
    CRYPTO_GENERICHASH_KEYBYTES = ParagonIE_Sodium_Compat.CRYPTO_GENERICHASH_KEYBYTES
    CRYPTO_GENERICHASH_KEYBYTES_MIN = ParagonIE_Sodium_Compat.CRYPTO_GENERICHASH_KEYBYTES_MIN
    CRYPTO_GENERICHASH_KEYBYTES_MAX = ParagonIE_Sodium_Compat.CRYPTO_GENERICHASH_KEYBYTES_MAX
    CRYPTO_SCALARMULT_BYTES = ParagonIE_Sodium_Compat.CRYPTO_SCALARMULT_BYTES
    CRYPTO_SCALARMULT_SCALARBYTES = ParagonIE_Sodium_Compat.CRYPTO_SCALARMULT_SCALARBYTES
    CRYPTO_SHORTHASH_BYTES = ParagonIE_Sodium_Compat.CRYPTO_SHORTHASH_BYTES
    CRYPTO_SHORTHASH_KEYBYTES = ParagonIE_Sodium_Compat.CRYPTO_SHORTHASH_KEYBYTES
    CRYPTO_SECRETBOX_KEYBYTES = ParagonIE_Sodium_Compat.CRYPTO_SECRETBOX_KEYBYTES
    CRYPTO_SECRETBOX_MACBYTES = ParagonIE_Sodium_Compat.CRYPTO_SECRETBOX_MACBYTES
    CRYPTO_SECRETBOX_NONCEBYTES = ParagonIE_Sodium_Compat.CRYPTO_SECRETBOX_NONCEBYTES
    CRYPTO_SIGN_BYTES = ParagonIE_Sodium_Compat.CRYPTO_SIGN_BYTES
    CRYPTO_SIGN_SEEDBYTES = ParagonIE_Sodium_Compat.CRYPTO_SIGN_SEEDBYTES
    CRYPTO_SIGN_PUBLICKEYBYTES = ParagonIE_Sodium_Compat.CRYPTO_SIGN_PUBLICKEYBYTES
    CRYPTO_SIGN_SECRETKEYBYTES = ParagonIE_Sodium_Compat.CRYPTO_SIGN_SECRETKEYBYTES
    CRYPTO_SIGN_KEYPAIRBYTES = ParagonIE_Sodium_Compat.CRYPTO_SIGN_KEYPAIRBYTES
    CRYPTO_STREAM_KEYBYTES = ParagonIE_Sodium_Compat.CRYPTO_STREAM_KEYBYTES
    CRYPTO_STREAM_NONCEBYTES = ParagonIE_Sodium_Compat.CRYPTO_STREAM_NONCEBYTES
# end class
